version: '3.9'

services:
    web:
        container_name: boutique-website
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
